### ISSUE TITLE
NPM Installation Failing - package not found

### ISSUE THREAD

**Issue by corner22** [narainsagar/angular2-ie9-shims#3]
Your readme installation instructions for npm are wrong.  the installation command must be lowercase, therefore must be:

npm install angular2-ie9-shims

**Comment by narainsagar** [comment]
Hi @corner22 I don't think, It will cause any issue. Both are acceptable though.

See here: 
![screen shot 2016-11-30 at 2 09 14 pm](https://cloud.githubusercontent.com/assets/13800762/20746281/f437b21c-b706-11e6-9692-69137da5593d.png)

And Yeah I also think that it's good to be all in lowercase.

So, I will update it.

Thanks.

**Comment by corner22** [comment]
@narainsagar. I executed exactly the same command-line as your post but got an error saying that uppercase names were not allowed.  Sorry, I don't have the exact msg to demonstrate as not in front of my PC right now.  I recently upgraded to latest version of npm and node on my Windows machine so perhaps that explains the difference.

**Comment by narainsagar** [comment]
Oh Yes, that probably be of older npm and node version.

Anyways, I will surely update the doc.

Thanks.
